// src/app/layout.tsx
import "./styles/globals.css";
import Navbar from "@/components/common/navbar/Navbar";
import type { Metadata } from "next";
import Providers from "./providers";
import ClarityProvider from "./ClarityProvider";

export const metadata: Metadata = {
  title: "Trynic",
  description: "Generated by songseungju",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <ClarityProvider />
        <Providers>
          <Navbar />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
