// app/layout.tsx
import "./styles/globals.css";
import Navbar from "@/components/common/navbar/Navbar";
import { AuthProvider } from "@/pages/user/AuthContext";
import type { Metadata } from "next";
import { CreditProvider } from "@/pages/payment/context/CreditContext";

export const metadata: Metadata = {
  title: "Trynic",
  description: "Generated by songseungju",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <CreditProvider>
          <AuthProvider>
            <Navbar />
            <div>{children}</div>
          </AuthProvider>
        </CreditProvider>
      </body>
    </html>
  );
}
