name: Deploy Front (Next.js → CodeDeploy)

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2
  BUCKET: trynic-front-git
  APP_NAME: trynic-front
  GROUP_NAME: trynic-front-group

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) clone
      - uses: actions/checkout@v4

      # 2) Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # 3) secret → .env.production
      - name: Create .env.production
        run: |
          cat <<EOF > .env.production
          NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
          FAL_KEY=${{ secrets.FAL_KEY }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          EOF

      # 4) install & build (stand-alone)
      - run: npm ci
      - run: npm run build -- --no-lint        # .next/standalone 생성

      # 5) make hooks executable
      - run: chmod +x codedeploy/*.sh

      # 6) bundle -- only what we need
      - name: Zip bundle
        run: |
          mkdir bundle
          # runtime 코드
          cp -r .next/standalone/* bundle/
          # 정적 리소스
          mkdir -p bundle/.next && cp -r .next/static bundle/.next/
          cp -r public bundle/
          # 설정·스크립트
          cp .env.production next.config.js package.json bundle/
          cp -r codedeploy appspec.yml bundle/
          cd bundle && zip -r ../trynic-front.zip .

      # 7) creds
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      # 8) S3 업로드
      - run: aws s3 cp trynic-front.zip s3://$BUCKET/trynic-front.zip

      # 9) CodeDeploy
      - run: |
          aws deploy create-deployment \
            --application-name $APP_NAME \
            --deployment-group-name $GROUP_NAME \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=$BUCKET,key=trynic-front.zip,bundleType=zip
